"""add campaign_templates table

Revision ID: 0b749a612b1b
Revises: 5a3844be2cb4
Create Date: 2026-10-01 15:04:01.502933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b749a612b1b'
down_revision = '5a3844be2cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('category', sa.Enum('promotion', 'bienvenue', 'relance', 'evenement', 'anniversaire', 'info', 'autre', name='campaign_template_category'), nullable=False),
    sa.Column('default_message', sa.Text(), nullable=True),
    sa.Column('default_template_id', sa.Integer(), nullable=True),
    sa.Column('default_media_file_id', sa.Integer(), nullable=True),
    sa.Column('default_timezone', sa.String(length=64), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_media_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_templates_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_templates_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_templates_is_public'))
        batch_op.drop_index(batch_op.f('ix_campaign_templates_category'))
        batch_op.drop_index(batch_op.f('ix_campaign_templates_business_id'))

    op.drop_table('campaign_templates')
    # ### end Alembic commands ###
