"""add ai_configs table

Revision ID: 5a3844be2cb4
Revises: 1ad70861e66e
Create Date: 2026-09-29 16:49:57.803126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3844be2cb4'
down_revision = '1ad70861e66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'groq', 'custom', name='ai_provider'), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('reply_language', sa.String(length=10), nullable=True),
    sa.Column('max_requests_per_month', sa.Integer(), nullable=True),
    sa.Column('requests_this_month', sa.Integer(), nullable=False),
    sa.Column('reset_quota_at', sa.DateTime(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_configs_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_configs_is_enabled'), ['is_enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_configs_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_ai_configs_business_id'))

    op.drop_table('ai_configs')
    # ### end Alembic commands ###
