"""add avatar_path to users

Revision ID: 91eec92a880e
Revises: 13816eef4477
Create Date: 2026-09-25 21:39:03.777653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eec92a880e'
down_revision = '13816eef4477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###
