"""add payment_url and provider_response to payments

Revision ID: 96f0a915db0b
Revises: cff372cbeb14
Create Date: 2026-09-26 12:34:20.803405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96f0a915db0b'
down_revision = 'cff372cbeb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('provider_response', sa.Text(), nullable=True))
        batch_op.drop_column('payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_column('provider_response')
        batch_op.drop_column('payment_url')

    # ### end Alembic commands ###
