"""add 2FA fields to users

Revision ID: b81ae4354869
Revises: 96f0a915db0b
Create Date: 2026-09-28 20:15:30.863066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81ae4354869'
down_revision = '96f0a915db0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('totp_backup_codes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_totp_enabled'), ['totp_enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_totp_enabled'))
        batch_op.drop_column('totp_confirmed_at')
        batch_op.drop_column('totp_backup_codes')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
