"""add chatbot tables

Revision ID: cff372cbeb14
Revises: 91eec92a880e
Create Date: 2026-09-25 23:18:24.105099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff372cbeb14'
down_revision = '91eec92a880e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.String(length=1000), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Enum('exact', 'contains', 'starts_with', name='chatbot_match_type'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('send_menu', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_rules_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_rules_priority'), ['priority'], unique=False)

    op.create_table('chatbot_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'waiting', 'human', 'closed', name='chatbot_conv_status'), nullable=False),
    sa.Column('trigger_message', sa.Text(), nullable=True),
    sa.Column('auto_replies_count', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_chatbot_conv_business_status', ['business_id', 'status'], unique=False)
        batch_op.create_index('idx_chatbot_conv_contact', ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversations_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversations_created_at'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversations_contact_id'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversations_business_id'))
        batch_op.drop_index('idx_chatbot_conv_contact')
        batch_op.drop_index('idx_chatbot_conv_business_status')

    op.drop_table('chatbot_conversations')
    with op.batch_alter_table('chatbot_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_chatbot_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_chatbot_rules_business_id'))

    op.drop_table('chatbot_rules')
    # ### end Alembic commands ###
