"""add media_file_id to campaigns

Revision ID: e15d1a63cca4
Revises: 28eae5ff020c
Create Date: 2026-09-29 10:51:47.340804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15d1a63cca4'
down_revision = '28eae5ff020c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_file_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaigns_media_file_id'), ['media_file_id'], unique=False)
        batch_op.create_foreign_key(None, 'media_files', ['media_file_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_campaigns_media_file_id'))
        batch_op.drop_column('media_file_id')

    # ### end Alembic commands ###
